apiVersion: apps/v1
kind: Deployment
metadata:
  name: jokes-client-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      name: jokes-client
  template:
    metadata:
      labels:
        name: jokes-client
    spec:
      containers:
      - name: jokes-client-container
        image: anujb2001/jokes-client
        ports:
          - containerPort: 3000
